elixir/howto/_old/phoenix_new/snippets/lib/my_app_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router
  use Plug.ErrorHandler # for Rollbax
  import MyAppWeb.AuthPlugs, only: [load_current_user: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :load_current_user
  end

  # Note: auth relies on the browser cookie session for now, so this isn't a full api.
  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :load_current_user
  end

  # In dev, preview all "sent" emails at localhost:4000/sent_emails
  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", MyAppWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/error", PageController, :error
    get "/privacy", PageController, :privacy
    get "/terms", PageController, :terms

    get "/auth/signup", AuthController, :signup
    post "/auth/signup", AuthController, :signup_submit
    get "/auth/login", AuthController, :login
    post "/auth/login", AuthController, :login_submit
    get "/auth/logout", AuthController, :logout
    get "/auth/request_email_confirm", AuthController, :request_email_confirm
    post "/auth/request_email_confirm", AuthController, :request_email_confirm_submit
    get "/auth/confirm_email", AuthController, :confirm_email
    get "/auth/request_password_reset", AuthController, :request_password_reset
    post "/auth/request_password_reset", AuthController, :request_password_reset_submit
    get "/auth/reset_password", AuthController, :reset_password
    post "/auth/reset_password", AuthController, :reset_password_submit

    get "/account/edit", UserController, :edit
    patch "/account/update", UserController, :update
    patch "/account/update_email", UserController, :update_email
  end

  # scope "/api", MyAppWeb, as: :api do
  #   pipe_through :api
  #   get "/groups/:uuid/progress", Api.GroupController, :progress
  #   post "/responses/:uuid/done", Api.ResponseController, :done
  # end

  defp handle_errors(conn, data), do: MyAppWeb.ErrorPlugs.handle_errors(conn, data)
end

elixir/howto/_old/phoenix_new/snippets/lib/my_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Grassflog</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <%= link "MyApp", to: "#", class: "navbar-brand" %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar-content">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbar-content" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto"></ul>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link "Some page", to: "#", class: "nav-link" %></li>

          <%= if @current_user do %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                <i class="icon">account_circle</i> <span class="caret"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-item em small"><%= gettext "Logged in as" %> <%= @current_user.email %></div>
                <%= link "Account settings", to: Routes.user_path(@conn, :edit), class: "dropdown-item" %>
                <%= link "Log out", to: Routes.auth_path(@conn, :logout), class: "dropdown-item text-danger" %>
              </div>
            </li>

          <% else %>

            <li class="nav-item"><%= link gettext("Sign up"), to: Routes.auth_path(@conn, :signup), class: "nav-link" %></li>
            <li class="nav-item"><%= link gettext("Log in"), to: Routes.auth_path(@conn, :login), class: "nav-link" %></li>

          <% end %>

        </ul>
      </div>
    </nav>

    <main class="container-fluid">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>

      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer class="text-center small">
      Built by <%= link "Topher Hunt", to: "http://topherhunt.com", target: "_blank" %>
    </footer>
  </body>
</html>

elixir/howto/_old/phoenix_new/snippets/lib/my_app_web/templates/layout/email.html.eex
<html>
  <head>
    <style>
    </style>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>